export const BATTLE: {[key:string]: string} = {
    SET_PLAYER_DATA: 'BATTLE.SET_PLAYER_DATA',
    SET_PLAYER2_DATA: 'BATTLE.SET_PLAYER2_DATA',
    HANDLE_RESET: 'BATTLE.HANDLE_RESET',
    HANDLE_RESET2: 'BATTLE.HANDLE_RESET2',
    GET_USERNAME: 'BATTLE.GET_USERNAME',
    GET_USERNAME2: 'BATTLE.GET_USERNAME2',
    SET_LOADING: 'BATTLE.SET_LOADING',
    GET_PARAMS_SUCCESS: 'BATTLE.GET_PARAMS_SUCCESS',
    GET_PARAMS_FAILURE: 'BATTLE.GET_PARAMS_FAILURE',
    RESET_LOADING: 'BATTLE.RESET_LOADING',
    SET_WINNER: 'BATTLE.SET_WINNER',
    SET_LOSER: 'BATTLE.SET_LOSER',
}